name: Build Pacman Package

on:
  push:
    paths:
      - 'pacman/**'
  pull_request:
    paths:
      - 'pacman/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Build Pacman Package
      run: |
        cd pacman
        makepkg -fs
    
    - name: Upload Pacman Package Artifact
      uses: actions/upload-artifact@v2
      with:
        name: pacman-package
        path: ./pacman/*.pkg.tar.xz
