name: Build APT Package

on:
  push:
    paths:
      - 'apt/**'
  pull_request:
    paths:
      - 'apt/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y dpkg-dev debhelper

    - name: Build APT Package
      run: |
        cd apt
        dpkg-deb --build . package

    - name: Upload APT Package Artifact
      uses: actions/upload-artifact@v2
      with:
        name: apt-package
        path: ./apt/package.deb
