name: Build Pacman Package

on:
  push:
    paths:
      - 'pacman/**'
  pull_request:
    paths:
      - 'pacman/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Build Pacman Package
      run: |
        cd pacman
        makepkg -fs
    
    - name: Upload Pacman Package to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./pacman/*.pkg.tar.xz
        asset_name: pacman-package.pkg.tar.xz
        asset_content_type: application/x-xz
